### ISSUE TITLE
BUG_Language Problems with Amount Keyboard

### ISSUE THREAD

**Issue by Roxas2712** [victorbalssa/abacus#28]
**Describe the bug**
The problem I face is that our German use of decimal keyboard has , instead of . for separating the decimal area. For example: If I need to add 8,41€ we would do that with , sperating the Euro and the Cents. The systems is expecting a . - That means 8.41€ instead.

**To Reproduce**
1. Go to New Transaction
2. Try to add a new amount with German Keyboard
3. See that we have only , as separators suggested

**Expected behavior**
i would expect the system to accept also , as separator for decimals  depending on the used keyboard. 
Even a switch of the keyboard has no improvements. Maybe this will be fixed with the languages coming. 

**Screenshots**
![6CA29CBC-EDB2-4246-AAB9-E04595063C76](https://user-images.githubusercontent.com/41802861/182800495-db54b36f-3fac-48ea-af02-106b7be2917f.jpeg)

![BE2AEC7F-F7BC-4E92-818C-E776A939134C](https://user-images.githubusercontent.com/41802861/182800028-4a460a73-3df2-4084-b100-aa673094f9ca.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 15.6

**Additional context**

**Comment by victorbalssa** [comment]
Fixed #30.

**Comment by Roxas2712** [comment]
Hello, after I updated the app it’s unfortunately still not working and I can’t enter a comma as seperator instead of a dot. (Like the German keyboard is working.

![42983147-E79F-481C-BFD8-300F3805E96F](https://user-images.githubusercontent.com/41802861/184328281-2d417813-3d1e-4111-8e71-d3b46b85e482.jpeg)


Im sure i have updated, because description auto fill works pretty awesome :)

**Comment by victorbalssa** [comment]
@Roxas2712 I created a new update "over the air".

Can you kill your app, restart and accept the update on launch?

It should work after updating.

**Comment by Roxas2712** [comment]
@victorbalssa We have done that on both devices . The pop up came up and we installed. But still the same issue.

![6E022955-10F7-4335-ADE3-A81974A8A5BD](https://user-images.githubusercontent.com/41802861/184379494-f46d64cc-b776-488b-b7c5-3ee4a817a7c9.jpeg)

**Comment by victorbalssa** [comment]
@Roxas2712 ok I can't fix it without modifying the keyboard.

Can you restart your app one more time?

**Comment by Roxas2712** [comment]
@victorbalssa 

Now it’s closed. Great work! Thank you :)

![Uploading 287C40B2-555A-4F63-AE82-B920EFB8878C.png…]()
